import {defineField, defineType} from 'sanity'
import {ImageWithAIButton} from '../components/ImageWithAIButton'
import {aiAutoFillAction} from '../actions/aiAutoFillAction'

export const archiveEntry = defineType({
  name: 'archiveEntry',
  title: 'Archive',
  preview: {
    select: {
      title: 'artName',
    },
  },
  type: 'document',
  actions: [aiAutoFillAction],
  fields: [
    defineField({
      name: 'year',
      title: 'Year',
      type: 'number',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'artName',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'artName',
      title: 'Art Name',
      type: 'string',
    }),
    defineField({
      name: 'aiDescription',
      title: 'AI Description',
      type: 'text',
      description: 'Description generated by AI from the image',
      readOnly: true,
    }),
    defineField({
      name: 'fileName',
      title: 'File Name',
      type: 'string',
    }),
    defineField({
      name: 'source',
      title: 'Source/Author',
      type: 'string',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [
        {
          type: 'reference',
          to: [{type: 'tag'}],
        },
      ],
      options: {
        layout: 'tags',
      },
    }),
    defineField({
      name: 'aiMoodTags',
      title: 'AI Mood Tags',
      type: 'array',
      of: [
        {
          type: 'string',
        },
      ],
      description: 'Mood tags generated by AI from the image',
      readOnly: true,
      options: {
        layout: 'tags',
      },
    }),
    defineField({
      name: 'poster',
      title: 'Poster',
      type: 'image',
      options: {
        hotspot: true
      },
      components: {
        input: ImageWithAIButton
      }
    }),
  ],
})